version: '3'
services:
  db:
    image: mysql:latest
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=100519Mi
      - MYSQL_DATABASE=bdrestaurante
      - MYSQL_USER=root
      - MYSQL_PASSWORD=100519Mi